server:
  port: 9411
logging.pattern.console: "%d{&quot;yyyy-MM-dd'T'HH:mm:ss.SSSZ&quot;} %highlight(%-5level) [%thread] rid=[%X{rid}] %logger{36} - %msg %rEx{30}%n"
pitchfork:
  validators:
    accept-null-timestamps: true
    max-timestamp-drift-seconds: -1
  ingress:
    kafka:
      enabled: false
      poll-duration-ms: 1000
      number-consumers: 4
      bootstrap-servers: kafka-service:9092
      source-topics:
        - zipkin
      source-format: JSON_V2
      overrides:
        auto-commit-internal-ms: 1000
        enable-auto-commit: true
        auto-offset-reset: "earliest"
        session-timeout-ms: 60000
    rabbitmq:
      enabled: false
      auto-ack: true
      user: guest
      password: guest
      virtual-host: "/"
      host: localhost
      port: 5672
      queue-name: zipkin
      source-format: JSON_V2
  forwarders:
    datadog:
      enabled: false
      host: localhost
      port: 8126
      connect-timeout-ms: 10000
      read-timeout-ms: 1000
      max-connections: 50
      queued-max-spans: 1000
    haystack:
      kinesis:
        enabled: false
        stream-name: "proto-spans"
        auth:
          config-type: DEFAULT
          basic:
            aws-access-key: "accesskey"
            aws-secret-key: "secretkey"
        client:
          config-type: REGION
          region:
            region-name: "us-west-1"
          endpoint:
            signing-region-name: "us-west-1"
            service-endpoint: "https://kinesis.us-west-1.amazonaws.com"
      kafka:
        enabled: false
        bootstrap-servers: kafka-service:9092
        topic: proto-spans
        overrides:
          batch.size: 256000
          linger.ms: 500
    logging:
      enabled: false
      log-full-span: false
    zipkin:
      http:
        enabled: false
        endpoint: http://localhost:9411/api/v2/spans
        max-inflight-requests: 256
        write-timeout-millis: 10000
        compression-enabled: true
        max-idle-connections: 50
        ignore-ssl-errors: false
        queued-max-spans: 1000
        encoding: JSON

management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
      graphite:
        enabled: false
        host: localhost
        port: 2004
        rate-units: milliseconds
        protocol: plaintext
        step: 1m
        tags-as-prefix:
          - "application"
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /
  endpoint:
    prometheus.enabled: true
    info:
      cache:
        time-to-live: 5s
    health:
      show-details: ALWAYS
      cache:
        time-to-live: 5s

info:
  app:
    name: Pitchfork
    description: Pitchfork lifts Zipkin tracing data into Haystack.
    readme: https://expediagroup.github.io/pitchfork/

spring:
  application:
    name: pitchfork
  codec:
    max-in-memory-size: 10MB
